### ISSUE TITLE
Error: ElasticSearch object has no attribute bulk_upload_sync

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-mordred#116]
When launching mordred for CHAOSS, with 18.03-03 packages, I get the following error:

```
Elasticsearch aliases for pipermail: creating...
Elasticsearch aliases for pipermail: created!
Enrichment for pipermail: finished after 00:00:10 hours
2018-03-20 22:47:28,881 - mordred.task_manager - ERROR - Exception in Task Manager 'ElasticSearch' object has no attribute 'bulk_upload_sync'
Exception in thread pipermail:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_manager.py", line 92, in run
    task.execute()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 257, in execute
    self.__autorefresh()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 178, in __autorefresh
    enrich_backend.elastic.bulk_upload_sync(eitems, field_id)
AttributeError: 'ElasticSearch' object has no attribute 'bulk_upload_sync'
```

This happens for all the data sources. It seems that something is happening with the `ElasticSearch` object...

**Comment by acs** [comment]
Fixed in https://github.com/chaoss/grimoirelab-mordred/commit/8cca2bec8e13db821630276633ae9ba550e7f3a0

Thanks @jgbarah
