### ISSUE TITLE
Latest version of mordred doesn't work with latest version of elk

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-mordred#99]
When launching master/HEAD of mordred, with master/HEAD of GrimoireELK:

```
Starting Mordred to build a GrimoireLab dashboard
This will usually take a while...
Traceback (most recent call last):
  File "/usr/local/bin/mordred", line 39, in <module>
    from mordred.mordred import Mordred
  File "/usr/local/lib/python3.5/dist-packages/mordred/mordred.py", line 47, in <module>
    from mordred.task_enrich import TaskEnrich
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 33, in <module>
    from grimoire_elk.elk.elastic import ElasticSearch
ImportError: No module named 'grimoire_elk.elk.elastic'
Failed to start Mordred: 1
```

I look in GrimoireELK and it seems `grimoire_elk/elk/elastic.py` is not there anymore...

**Comment by acs** [comment]
This was already fixed in:

https://github.com/chaoss/grimoirelab-mordred/pull/96

**Comment by acs** [comment]
Ups, no, this was fixed in 

https://github.com/chaoss/grimoirelab-mordred/pull/98

but it is pending for a review to merge it!

**Comment by jgbarah** [comment]
Piece of cake ;-)

Done.
